apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: sigemad
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
