apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dsmarkromero/sigemad-back:v1.01
          ports:
            - containerPort: 8080
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: "http://+:8080"
