apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dsmarkromero/sigemad-backend:latest #
          ports:
            - containerPort: 80
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
