apiVersion: v1
kind: Service
metadata:
  name: svc-sqlserver
  namespace: sigemad
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
